source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.0"


# Core
gem "rails", "~> 7.0.4", ">= 7.0.4.3"
gem 'kaminari'
gem 'paranoia'
gem 'jquery-rails', "4.5.1"
gem 'select2-rails', '4.0.13'
gem 'coffee-rails', '~> 5.0.0'
gem "puma", "~> 5.0"
gem 'bootstrap'
gem "sassc-rails"
gem 'haml', '6.1.1'
gem 'haml-rails', '2.1.0'
gem "jbuilder"


# Turmo accelerator
gem "turbo-rails"
gem "stimulus-rails"
gem "importmap-rails"
gem "sprockets-rails"


# Auth
gem 'devise', '~> 4.8', '>= 4.8.1'


# Database
gem "pg", "~> 1.1"


# security
gem 'rack-attack'


# cache
# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false


# Others
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"
# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"
# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"
# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"


group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
